name: Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: "DecoratedWings"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Pac-Man contribution graph"
          file_pattern: "pacman-contribution-graph/*"
